version: "3.3"

services:
  spotify-vnc:
    image: dec0dos/spotify-vnc
    container_name: spotify-vnc
    build:
      context: .
    ports:
      - 5900:5900
    volumes:
      - type: bind
        source: .config
        target: /home/docker/.config/spotify
    #   - type: bind
    #     source: /tmp/snapfifo
    #     target: /tmp/snapfifo
    restart: unless-stopped
